"""Legacy-path regression guard (plan §1.3).

The legacy TADS score (score_mode: "tads", paper Eq. 10) is the baseline
arm of every low-quality-pool comparison, so its selection behaviour must
stay BIT-IDENTICAL while the MVF path evolves. These tests pin the legacy
scoring math against an independent re-derivation of the paper formulas —
not against a recorded output of the same code, so any drift in
``pool_reward`` / ``normalize_alignment`` / ``tads_score`` /
``select_top_b`` shows up as a failure with an explicit formula to check
against, whatever the cause.

The tiny-GPT-2 end-to-end legacy path is covered separately in
tests/test_selector_mvf.py::test_legacy_path_unchanged_and_vectors_exposed.
"""
from __future__ import annotations

import torch

from tads.core.scorer import (
    normalize_alignment,
    pool_reward,
    select_top_b,
    tads_score,
)


def _synthetic_pool(n=64, seed=1234):
    g = torch.Generator().manual_seed(seed)
    loss = torch.rand(n, generator=g) * 3.0 + 0.5
    entropy = torch.rand(n, generator=g) * 1.5 + 0.2
    align_raw = torch.randn(n, generator=g)
    return loss, entropy, align_raw


def test_legacy_pool_reward_formula():
    """R_i = w·L_i + (1-w)·H_i with w = Var(L)/(Var(L)+Var(H)+ε), variances
    over the FULL pool (paper Eqs. 3-4)."""
    loss, entropy, _ = _synthetic_pool()
    R, w = pool_reward(loss, entropy)
    var_l = loss.var().item()
    var_h = entropy.var().item()
    w_expected = var_l / (var_l + var_h + 1e-8)
    assert abs(w - w_expected) < 1e-12
    assert torch.allclose(R, w_expected * loss + (1 - w_expected) * entropy)


def test_legacy_alignment_minmax_formula():
    """Legacy alignment stays MIN-MAX normalised (paper §3.3) — the MVF
    path's pool-CDF normalisation must not leak into the legacy path."""
    _, _, align_raw = _synthetic_pool()
    a, collapsed = normalize_alignment(align_raw)
    assert not collapsed
    expected = (align_raw - align_raw.min()) / (align_raw.max() - align_raw.min())
    assert torch.allclose(a, expected)
    assert float(a.min()) == 0.0 and float(a.max()) == 1.0


def test_legacy_score_and_selection_golden():
    """Full legacy composition on a fixed synthetic pool: score and top-B
    membership re-derived from the paper formulas."""
    loss, entropy, align_raw = _synthetic_pool()
    lam = 1.0
    R, w = pool_reward(loss, entropy)
    align, _ = normalize_alignment(align_raw)
    s = tads_score(R, align, lam)
    assert torch.allclose(s, R * (1.0 + lam * align))
    # Independent top-B: sort by score descending, stable.
    b = 16
    got = select_top_b(s, b).tolist()
    expected = torch.argsort(s, descending=True, stable=True)[:b].tolist()
    assert sorted(got) == sorted(expected)
    # Ranking sanity pinned: λ=0 recovers the composite-reward ranking.
    s0 = tads_score(R, align, 0.0)
    assert torch.equal(
        torch.argsort(s0, descending=True, stable=True),
        torch.argsort(R, descending=True, stable=True),
    )


def test_legacy_selection_hardcoded_golden():
    """Bit-level golden: the exact top-16 indices the legacy pipeline
    selected on _synthetic_pool(n=64, seed=1234) at the time this test was
    written. Unlike the formula re-derivations above (which recompute the
    expectation from the same primitives and could drift in lock-step with
    the implementation), this literal list pins the OUTPUT itself.

    Regenerate ONLY with an explicit changelog entry: if this fails, the
    legacy selection changed, and that is either a real regression or a
    deliberate, documented break of the low-quality-pool baseline arm.
    """
    loss, entropy, align_raw = _synthetic_pool(n=64, seed=1234)
    R, _ = pool_reward(loss, entropy)
    align, _ = normalize_alignment(align_raw)
    s = tads_score(R, align, 1.0)
    got = select_top_b(s, 16).tolist()
    # Generated by running pool_reward → normalize_alignment →
    # tads_score(lam=1.0) → select_top_b(16) on this exact fixture
    # (torch CPU, score-descending order).
    golden = [61, 38, 36, 48, 51, 54, 12, 15, 35, 32, 42, 13, 5, 52, 17, 50]
    assert got == golden


def test_legacy_score_no_rank_transform():
    """The legacy path must not pick up rank/CDF/sigmoid transforms from the
    MVF additions (paper §3.3: 'No learned transform, learned policy,
    z-score, or sigmoid is applied inside the ranking rule')."""
    loss, entropy, align_raw = _synthetic_pool()
    R, _ = pool_reward(loss, entropy)
    align, _ = normalize_alignment(align_raw)
    s = tads_score(R, align, 0.7)
    # Raw-scale property: doubling R doubles the score (rank transforms
    # would break positive homogeneity in R).
    s2 = tads_score(R * 2.0, align, 0.7)
    assert torch.allclose(s2, s * 2.0)
