model_key: deepseek-7b
model_path: ${oc.env:MODEL_PATH_DEEPSEEK_7B,/group-volume/nait-models/deepseek-llm-7b-base}
prompt_style: deepseek_user_assistant
max_seq_len: 2048
# DeepSeek-LLM Technical Report SFT recipe.
learning_rate: 2.0e-5
